// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwcUWrVwl1Fzp72o5IJzJu-7KbShjpIxA',
    appId: '1:658113595675:web:48c33b3dca2012c0366bbe',
    messagingSenderId: '658113595675',
    projectId: 'chatapp-b4d7d',
    authDomain: 'chatapp-b4d7d.firebaseapp.com',
    storageBucket: 'chatapp-b4d7d.appspot.com',
    measurementId: 'G-CBQJ57N4J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAeD1LxLryjvXt5fKUAlWSYrqunpw9FA',
    appId: '1:658113595675:android:d885b87aee02a26f366bbe',
    messagingSenderId: '658113595675',
    projectId: 'chatapp-b4d7d',
    storageBucket: 'chatapp-b4d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJjDy8RSO32flyBOeqO4AQUMFILBqvyk',
    appId: '1:658113595675:ios:68b5c748a8dfcb18366bbe',
    messagingSenderId: '658113595675',
    projectId: 'chatapp-b4d7d',
    storageBucket: 'chatapp-b4d7d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJjDy8RSO32flyBOeqO4AQUMFILBqvyk',
    appId: '1:658113595675:ios:68b5c748a8dfcb18366bbe',
    messagingSenderId: '658113595675',
    projectId: 'chatapp-b4d7d',
    storageBucket: 'chatapp-b4d7d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwcUWrVwl1Fzp72o5IJzJu-7KbShjpIxA',
    appId: '1:658113595675:web:004101c12a83889a366bbe',
    messagingSenderId: '658113595675',
    projectId: 'chatapp-b4d7d',
    authDomain: 'chatapp-b4d7d.firebaseapp.com',
    storageBucket: 'chatapp-b4d7d.appspot.com',
    measurementId: 'G-64HWLFC2KK',
  );
}
